version: '3.11'

services:

  database:
    container_name: database
    image: postgres:latest
    volumes:
      - database_volume:/var/lib/postgresql/data/
    env_file:
      - ./src/.dbenv
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres


  backend:
    container_name: backend
    build: ./src
    command: bash -c "uvicorn run:app --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    depends_on:
      database:
        condition: "service_healthy"
    env_file:
      - ./src/.dev_env



volumes:
  database_volume: